# Generated by Django 4.2.7 on 2023-11-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='animal',
            name='discription',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='animal',
            name='eat',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='animal',
            name='price',
            field=models.IntegerField(default=2),
        ),
    ]
