# Generated by Django 4.2.7 on 2023-11-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_feeding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='feeding',
            old_name='cat',
            new_name='animal',
        ),
    ]
