# Generated by Django 4.2.7 on 2023-11-07 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_toy_country_rename_toys_animal_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='color',
        ),
    ]
